-- Source-controlled snapshot of the configurable TAD service workflow engine.
-- Production received this foundation in audited stages; this migration makes a
-- fresh install reproducible and adds templates for every supported department.

alter table public.service_engagements
  add column if not exists template_key text;

create table if not exists public.service_workflow_templates (
  key text primary key,
  department text not null unique check (department in ('invoice','sales','client','property','practice','member','core')),
  name text not null,
  version integer not null default 1,
  config jsonb not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.service_workflow_templates enable row level security;

create table if not exists public.service_work_items (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  engagement_id uuid not null references public.service_engagements(id) on delete cascade,
  department text not null check (department in ('invoice','sales','client','property','practice','member','core')),
  reference text not null,
  title text not null,
  status text not null,
  assigned_to uuid references auth.users(id) on delete set null,
  assigned_name text,
  priority integer not null default 50 check (priority between 0 and 100),
  next_action text,
  due_date date,
  blocked_reason text,
  data jsonb not null default '{}'::jsonb,
  last_outcome_code text,
  last_outcome_note text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, department, reference)
);
alter table public.service_work_items enable row level security;
create index if not exists service_work_items_queue_idx on public.service_work_items(business_id,status,due_date,priority desc);
create index if not exists service_work_items_engagement_idx on public.service_work_items(engagement_id,updated_at desc);
create index if not exists service_work_items_assigned_to_idx on public.service_work_items(assigned_to) where assigned_to is not null;

create table if not exists public.service_work_item_events (
  id bigint generated by default as identity primary key,
  work_item_id uuid not null references public.service_work_items(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text,
  note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.service_work_item_events enable row level security;
create index if not exists service_work_item_events_item_idx on public.service_work_item_events(work_item_id,created_at desc);
create index if not exists service_work_item_events_business_idx on public.service_work_item_events(business_id,created_at desc);

drop policy if exists "workflow template read" on public.service_workflow_templates;
drop policy if exists "workflow template operator insert" on public.service_workflow_templates;
drop policy if exists "workflow template operator update" on public.service_workflow_templates;
drop policy if exists "workflow template operator delete" on public.service_workflow_templates;
create policy "workflow template read" on public.service_workflow_templates for select to authenticated using (active);
create policy "workflow template operator insert" on public.service_workflow_templates for insert to authenticated with check (public.is_tad_operator());
create policy "workflow template operator update" on public.service_workflow_templates for update to authenticated using (public.is_tad_operator()) with check (public.is_tad_operator());
create policy "workflow template operator delete" on public.service_workflow_templates for delete to authenticated using (public.is_tad_operator());

drop policy if exists "work item read" on public.service_work_items;
drop policy if exists "work item insert" on public.service_work_items;
drop policy if exists "work item update" on public.service_work_items;
drop policy if exists "work item delete" on public.service_work_items;
create policy "work item read" on public.service_work_items for select to authenticated using (public.can_access_business(business_id));
create policy "work item insert" on public.service_work_items for insert to authenticated with check (public.can_work_business(business_id));
create policy "work item update" on public.service_work_items for update to authenticated using (public.can_work_business(business_id)) with check (public.can_work_business(business_id));
create policy "work item delete" on public.service_work_items for delete to authenticated using (public.can_manage_business(business_id));

drop policy if exists "work item event read" on public.service_work_item_events;
drop policy if exists "work item event insert" on public.service_work_item_events;
create policy "work item event read" on public.service_work_item_events for select to authenticated using (public.can_access_business(business_id));
create policy "work item event insert" on public.service_work_item_events for insert to authenticated with check (public.can_work_business(business_id));

grant select on public.service_workflow_templates to authenticated;
grant select,insert,update,delete on public.service_work_items to authenticated;
grant select,insert on public.service_work_item_events to authenticated;

insert into public.service_workflow_templates(key,department,name,version,config,active)
values
('invoice-admin-v1','invoice','Invoice Admin',1,'{"statuses":["New","Needs Capture","Missing Info","Possible Duplicate","Ready for Review","Waiting for Approval","Approved","Paid","Filed","Rejected"],"closed_statuses":["Paid","Filed","Rejected"],"fields":[{"key":"supplier_name","label":"Supplier","type":"text","required":true},{"key":"document_type","label":"Document type","type":"select","options":["Invoice","Receipt","Proof of Payment","Statement"]},{"key":"invoice_number","label":"Reference","type":"text"},{"key":"amount","label":"Amount","type":"number"},{"key":"approval_owner","label":"Approver","type":"text"},{"key":"document_link","label":"Document link","type":"url"}]}'::jsonb,true),
('sales-admin-v1','sales','Sales Admin',1,'{"statuses":["New","Needs Response","Contacted","Waiting for Client","Quote Needed","Quote Sent","Follow-up Due","Won","Lost","Cold","Closed"],"closed_statuses":["Won","Lost","Cold","Closed"],"fields":[{"key":"contact_name","label":"Contact","type":"text","required":true},{"key":"source","label":"Source","type":"text"},{"key":"service_needed","label":"Service needed","type":"text","required":true},{"key":"urgency","label":"Urgency","type":"select","options":["Low","Normal","High"]},{"key":"quote_amount","label":"Quote amount","type":"number"},{"key":"outcome_reason","label":"Outcome reason","type":"text"}]}'::jsonb,true),
('client-admin-v1','client','Client Admin',1,'{"statuses":["New Client","Welcome Sent","Documents Requested","Waiting for Client","Internal Setup","Payment/Agreement Pending","Ready to Start","Active","Stuck","Cancelled"],"closed_statuses":["Active","Cancelled"],"fields":[{"key":"client_name","label":"Client","type":"text","required":true},{"key":"service_package","label":"Package","type":"text"},{"key":"documents_received","label":"Documents received","type":"select","options":["No","Partial","Yes"]},{"key":"missing_documents","label":"Missing documents","type":"text"},{"key":"agreement_status","label":"Agreement","type":"select","options":["Pending","Sent","Signed","Not applicable"]},{"key":"payment_status","label":"Payment","type":"select","options":["Pending","Unpaid","Paid","Not applicable"]}]}'::jsonb,true),
('property-admin-v1','property','Property Admin',1,'{"statuses":["New Request","Tenant Contacted","Quote Needed","Quote Sent","Owner Approval","Approved","Scheduled","In Progress","Completed","Closed","Blocked","Cancelled"],"closed_statuses":["Completed","Closed","Cancelled"],"fields":[{"key":"property_name","label":"Property","type":"text","required":true},{"key":"unit","label":"Unit","type":"text"},{"key":"tenant_name","label":"Tenant","type":"text"},{"key":"request_type","label":"Request type","type":"text","required":true},{"key":"urgency","label":"Urgency","type":"select","options":["Low","Normal","High","Emergency"]},{"key":"owner_approval","label":"Owner approval","type":"select","options":["Pending","Approved","Rejected","Not required"]},{"key":"supplier","label":"Supplier","type":"text"},{"key":"proof_link","label":"Completion proof","type":"url"}]}'::jsonb,true),
('practice-admin-v1','practice','Practice / Booking Admin',1,'{"statuses":["New Booking","Needs Confirmation","Confirmed","Documents Needed","Payment Pending","Ready for Appointment","Completed","No-show","Cancelled","Follow-up Due"],"closed_statuses":["Completed","No-show","Cancelled"],"fields":[{"key":"client_reference","label":"Client reference","type":"text","required":true},{"key":"service","label":"Service","type":"text"},{"key":"channel","label":"Channel","type":"text"},{"key":"appointment_date","label":"Appointment date","type":"text"},{"key":"confirmation_sent","label":"Confirmation sent","type":"select","options":["No","Yes"]},{"key":"payment_status","label":"Payment","type":"select","options":["Pending","Unpaid","Paid","Not applicable"]},{"key":"no_show_risk","label":"No-show risk","type":"select","options":["Low","Normal","High"]}]}'::jsonb,true),
('member-admin-v1','member','Member Admin',1,'{"statuses":["New Member","Onboarding","Active","Attendance Risk","Payment Due","Follow-up Due","Reactivation","Retained","Cancelled","Dormant"],"closed_statuses":["Retained","Cancelled","Dormant"],"fields":[{"key":"member_name","label":"Member","type":"text","required":true},{"key":"plan","label":"Plan","type":"text"},{"key":"payment_status","label":"Payment","type":"select","options":["Pending","Unpaid","Paid","Not applicable"]},{"key":"last_attendance_date","label":"Last attendance","type":"text"},{"key":"onboarding_done","label":"Onboarding done","type":"select","options":["No","Yes","Not applicable"]},{"key":"risk_level","label":"Risk","type":"select","options":["Low","Normal","High"]},{"key":"outcome_reason","label":"Outcome reason","type":"text"}]}'::jsonb,true),
('core-admin-v1','core','Core Business Execution',1,'{"statuses":["New","Assigned","In Progress","Waiting","Blocked","Review","Completed","Cancelled"],"closed_statuses":["Completed","Cancelled"],"fields":[{"key":"workstream","label":"Workstream","type":"select","options":["Acquire","Convert","Deliver","Collect","Control","Improve","Lead"]},{"key":"customer_or_project","label":"Customer or project","type":"text"},{"key":"evidence_link","label":"Evidence link","type":"url"},{"key":"outcome_measure","label":"Outcome measure","type":"text"}]}'::jsonb,true)
on conflict (key) do update set name=excluded.name, version=excluded.version, config=excluded.config, active=excluded.active, updated_at=now();

update public.service_engagements
set template_key = department || '-admin-v1'
where template_key is null and department <> 'core';
update public.service_engagements set template_key='core-admin-v1' where template_key is null and department='core';

create or replace function public.get_service_workflow(p_business_id uuid)
returns jsonb language plpgsql security definer set search_path='' stable as $$
declare v_uid uuid:=auth.uid(); v_business public.businesses%rowtype; v_engagement public.service_engagements%rowtype; v_template public.service_workflow_templates%rowtype;
begin
  if v_uid is null or not public.can_access_business(p_business_id,v_uid) then raise exception 'business not accessible'; end if;
  select * into v_business from public.businesses where id=p_business_id;
  select * into v_engagement from public.service_engagements where business_id=p_business_id order by created_at desc limit 1;
  if v_engagement.id is null then raise exception 'service engagement not found'; end if;
  select * into v_template from public.service_workflow_templates where key=coalesce(v_engagement.template_key,case when v_engagement.department='core' then 'core-admin-v1' else v_engagement.department||'-admin-v1' end) and active;
  if v_template.key is null then raise exception 'workflow template not found'; end if;
  return jsonb_build_object('business',jsonb_build_object('id',v_business.id,'name',v_business.name,'industry',v_business.industry,'service_status',v_business.service_status),'engagement',jsonb_build_object('id',v_engagement.id,'department',v_engagement.department,'service_level',v_engagement.service_level,'status',v_engagement.status,'next_review_date',v_engagement.next_review_date),'template',jsonb_build_object('key',v_template.key,'name',v_template.name,'version',v_template.version,'config',v_template.config),'items',coalesce((select jsonb_agg(row_to_json(x) order by x.priority desc,x.due_date nulls last,x.updated_at desc) from(select wi.* from public.service_work_items wi where wi.business_id=p_business_id and wi.engagement_id=v_engagement.id)x),'[]'::jsonb));
end $$;

create or replace function public.create_service_work_item(p_business_id uuid,p_engagement_id uuid,p_reference text,p_title text,p_status text default null,p_assigned_name text default null,p_priority integer default 50,p_next_action text default null,p_due_date date default null,p_blocked_reason text default null,p_data jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=auth.uid(); v_engagement public.service_engagements%rowtype; v_template public.service_workflow_templates%rowtype; v_status text; v_reference text; v_item public.service_work_items%rowtype;
begin
  if v_uid is null or not public.can_work_business(p_business_id,v_uid) then raise exception 'business work access required'; end if;
  if nullif(trim(p_title),'') is null then raise exception 'title required'; end if;
  select * into v_engagement from public.service_engagements where id=p_engagement_id and business_id=p_business_id;
  if v_engagement.id is null then raise exception 'engagement not found'; end if;
  select * into v_template from public.service_workflow_templates where key=coalesce(v_engagement.template_key,case when v_engagement.department='core' then 'core-admin-v1' else v_engagement.department||'-admin-v1' end) and active;
  if v_template.key is null then raise exception 'workflow template not found'; end if;
  v_status:=coalesce(nullif(trim(p_status),''),v_template.config->'statuses'->>0);
  if not exists(select 1 from jsonb_array_elements_text(v_template.config->'statuses') s(value) where s.value=v_status) then raise exception 'invalid workflow status'; end if;
  v_reference:=coalesce(nullif(trim(p_reference),''),upper(left(v_engagement.department,3))||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)));
  insert into public.service_work_items(business_id,engagement_id,department,reference,title,status,assigned_name,priority,next_action,due_date,blocked_reason,data) values(p_business_id,p_engagement_id,v_engagement.department,left(v_reference,80),left(trim(p_title),240),v_status,nullif(trim(p_assigned_name),''),greatest(0,least(coalesce(p_priority,50),100)),nullif(trim(p_next_action),''),p_due_date,nullif(trim(p_blocked_reason),''),coalesce(p_data,'{}'::jsonb)) returning * into v_item;
  insert into public.service_work_item_events(work_item_id,business_id,actor_id,event_type,to_status,note,metadata) values(v_item.id,p_business_id,v_uid,'created',v_item.status,'Work item created',jsonb_build_object('reference',v_item.reference));
  return to_jsonb(v_item);
end $$;

create or replace function public.update_service_work_item(p_work_item_id uuid,p_status text,p_assigned_name text default null,p_priority integer default 50,p_next_action text default null,p_due_date date default null,p_blocked_reason text default null,p_data jsonb default '{}'::jsonb,p_note text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=auth.uid(); v_before public.service_work_items%rowtype; v_after public.service_work_items%rowtype; v_template public.service_workflow_templates%rowtype; v_closed boolean;
begin
  select * into v_before from public.service_work_items where id=p_work_item_id for update;
  if v_before.id is null then raise exception 'work item not found'; end if;
  if v_uid is null or not public.can_work_business(v_before.business_id,v_uid) then raise exception 'business work access required'; end if;
  select * into v_template from public.service_workflow_templates where department=v_before.department and active;
  if v_template.key is null then raise exception 'workflow template not found'; end if;
  if not exists(select 1 from jsonb_array_elements_text(v_template.config->'statuses') s(value) where s.value=p_status) then raise exception 'invalid workflow status'; end if;
  select exists(select 1 from jsonb_array_elements_text(v_template.config->'closed_statuses') s(value) where s.value=p_status) into v_closed;
  update public.service_work_items set status=p_status,assigned_name=nullif(trim(p_assigned_name),''),priority=greatest(0,least(coalesce(p_priority,priority),100)),next_action=nullif(trim(p_next_action),''),due_date=p_due_date,blocked_reason=nullif(trim(p_blocked_reason),''),data=coalesce(p_data,data),completed_at=case when v_closed then coalesce(completed_at,now()) else null end,updated_at=now() where id=p_work_item_id returning * into v_after;
  insert into public.service_work_item_events(work_item_id,business_id,actor_id,event_type,from_status,to_status,note,metadata) values(v_after.id,v_after.business_id,v_uid,case when v_before.status is distinct from v_after.status then 'status_changed' else 'updated' end,v_before.status,v_after.status,nullif(trim(p_note),''),jsonb_build_object('due_date',v_after.due_date,'assigned_name',v_after.assigned_name,'blocked',v_after.blocked_reason is not null));
  return to_jsonb(v_after);
end $$;

create or replace function public.reflect_service_workflow_outcome()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.entity_table='service_work_items' and new.entity_id is not null and (old.outcome_code is distinct from new.outcome_code or old.outcome_note is distinct from new.outcome_note or old.next_action_date is distinct from new.next_action_date) then
    update public.service_work_items set last_outcome_code=new.outcome_code,last_outcome_note=new.outcome_note,due_date=case when new.next_action_date is not null then new.next_action_date else due_date end,next_action=case when new.next_action_date is not null and new.outcome_note is not null then left(new.outcome_note,500) else next_action end,updated_at=now() where id=new.entity_id and business_id=new.business_id;
    insert into public.service_work_item_events(work_item_id,business_id,actor_id,event_type,note,metadata) values(new.entity_id,new.business_id,auth.uid(),'action_outcome',new.outcome_note,jsonb_build_object('outcome_code',new.outcome_code,'next_action_date',new.next_action_date,'action_id',new.id));
  end if;
  return new;
end $$;

drop trigger if exists actions_reflect_service_workflow_outcome on public.actions;
create trigger actions_reflect_service_workflow_outcome after update of outcome_code,outcome_note,next_action_date on public.actions for each row execute function public.reflect_service_workflow_outcome();

revoke all on function public.get_service_workflow(uuid) from public,anon;
revoke all on function public.create_service_work_item(uuid,uuid,text,text,text,text,integer,text,date,text,jsonb) from public,anon;
revoke all on function public.update_service_work_item(uuid,text,text,integer,text,date,text,jsonb,text) from public,anon;
grant execute on function public.get_service_workflow(uuid) to authenticated;
grant execute on function public.create_service_work_item(uuid,uuid,text,text,text,text,integer,text,date,text,jsonb) to authenticated;
grant execute on function public.update_service_work_item(uuid,text,text,integer,text,date,text,jsonb,text) to authenticated;
