-- Shared private workflow schema for every TAD managed department.

alter table public.service_engagements
  add column if not exists template_key text;

create table if not exists public.service_workflow_templates (
  key text primary key,
  department text not null unique
    check (department in ('invoice','sales','client','property','practice','member','core')),
  name text not null,
  version integer not null default 1,
  config jsonb not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.service_workflow_templates enable row level security;

create table if not exists public.service_work_items (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  engagement_id uuid not null references public.service_engagements(id) on delete cascade,
  department text not null
    check (department in ('invoice','sales','client','property','practice','member','core')),
  reference text not null,
  title text not null,
  status text not null,
  assigned_to uuid references auth.users(id) on delete set null,
  assigned_name text,
  priority integer not null default 50 check (priority between 0 and 100),
  next_action text,
  due_date date,
  blocked_reason text,
  data jsonb not null default '{}'::jsonb,
  last_outcome_code text,
  last_outcome_note text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id,department,reference)
);
alter table public.service_work_items enable row level security;
create index if not exists service_work_items_queue_idx
  on public.service_work_items(business_id,status,due_date,priority desc);
create index if not exists service_work_items_engagement_idx
  on public.service_work_items(engagement_id,updated_at desc);
create index if not exists service_work_items_assigned_to_idx
  on public.service_work_items(assigned_to) where assigned_to is not null;

create table if not exists public.service_work_item_events (
  id bigint generated by default as identity primary key,
  work_item_id uuid not null references public.service_work_items(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text,
  note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.service_work_item_events enable row level security;
create index if not exists service_work_item_events_item_idx
  on public.service_work_item_events(work_item_id,created_at desc);
create index if not exists service_work_item_events_business_idx
  on public.service_work_item_events(business_id,created_at desc);
create index if not exists service_work_item_events_actor_idx
  on public.service_work_item_events(actor_id) where actor_id is not null;

create policy "workflow template read" on public.service_workflow_templates
  for select to authenticated using (active);
create policy "workflow template operator insert" on public.service_workflow_templates
  for insert to authenticated with check (public.is_tad_operator());
create policy "workflow template operator update" on public.service_workflow_templates
  for update to authenticated
  using (public.is_tad_operator()) with check (public.is_tad_operator());
create policy "workflow template operator delete" on public.service_workflow_templates
  for delete to authenticated using (public.is_tad_operator());

create policy "work item read" on public.service_work_items
  for select to authenticated using (public.can_access_business(business_id));
create policy "work item insert" on public.service_work_items
  for insert to authenticated with check (public.can_work_business(business_id));
create policy "work item update" on public.service_work_items
  for update to authenticated
  using (public.can_work_business(business_id))
  with check (public.can_work_business(business_id));
create policy "work item delete" on public.service_work_items
  for delete to authenticated using (public.can_manage_business(business_id));

create policy "work item event read" on public.service_work_item_events
  for select to authenticated using (public.can_access_business(business_id));
create policy "work item event insert" on public.service_work_item_events
  for insert to authenticated with check (public.can_work_business(business_id));

grant select on public.service_workflow_templates to authenticated;
grant select,insert,update,delete on public.service_work_items to authenticated;
grant select,insert on public.service_work_item_events to authenticated;
