-- Secure TAD Sales Admin application intake and operator onboarding pipeline.
-- Public applicants can only call one narrow submission RPC. All review and
-- onboarding actions require an authenticated active TAD operator.

create table if not exists public.tad_applications (
  id uuid primary key default gen_random_uuid(),
  business_name text not null check (char_length(business_name) between 2 and 160),
  contact_name text not null check (char_length(contact_name) between 2 and 160),
  email text not null check (char_length(email) between 5 and 320),
  active_records integer not null check (active_records between 0 and 10000),
  follow_up_problem text not null check (follow_up_problem in (
    'missed', 'ownership', 'next_action', 'visibility', 'reporting', 'none'
  )),
  current_tools text,
  required_outcome text not null check (char_length(required_outcome) between 5 and 700),
  owner_available boolean not null,
  data_authority boolean not null,
  boundary_accepted boolean not null,
  readiness_score integer not null check (readiness_score between 0 and 10),
  readiness_ready boolean not null default false,
  status text not null default 'new' check (status in (
    'new', 'reviewing', 'qualified', 'declined', 'onboarding', 'converted'
  )),
  qualification_notes text,
  commercial_decision text not null default 'pending' check (commercial_decision in (
    'pending', 'accepted', 'declined', 'needs_scope'
  )),
  managed_business_id uuid references public.businesses(id) on delete set null,
  source text not null default 'sales_admin_offer',
  request_fingerprint text not null,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tad_applications enable row level security;
create index if not exists tad_applications_status_idx
  on public.tad_applications(status, submitted_at desc);
create index if not exists tad_applications_email_idx
  on public.tad_applications(lower(email), submitted_at desc);
create index if not exists tad_applications_fingerprint_idx
  on public.tad_applications(request_fingerprint, submitted_at desc);
create unique index if not exists tad_applications_managed_business_unique
  on public.tad_applications(managed_business_id)
  where managed_business_id is not null;

create table if not exists public.tad_application_events (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.tad_applications(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text,
  detail text,
  created_at timestamptz not null default now()
);

alter table public.tad_application_events enable row level security;
create index if not exists tad_application_events_application_idx
  on public.tad_application_events(application_id, created_at desc);

create policy "operators read TAD applications" on public.tad_applications
  for select using (public.is_tad_operator());
create policy "operators read TAD application events" on public.tad_application_events
  for select using (public.is_tad_operator());

revoke all on table public.tad_applications from anon, authenticated;
revoke all on table public.tad_application_events from anon, authenticated;

create or replace function public.touch_tad_application_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.touch_tad_application_updated_at() from public, anon, authenticated;

drop trigger if exists tad_applications_touch_updated_at on public.tad_applications;
create trigger tad_applications_touch_updated_at
before update on public.tad_applications
for each row execute function public.touch_tad_application_updated_at();

create or replace function public.submit_tad_application(
  p_business_name text,
  p_contact_name text,
  p_email text,
  p_active_records integer,
  p_follow_up_problem text,
  p_current_tools text,
  p_required_outcome text,
  p_owner_available boolean,
  p_data_authority boolean,
  p_boundary_accepted boolean,
  p_request_fingerprint text,
  p_source text default 'sales_admin_offer'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing public.tad_applications%rowtype;
  v_application public.tad_applications%rowtype;
  v_score integer := 0;
  v_ready boolean := false;
  v_email text := lower(trim(coalesce(p_email, '')));
begin
  if nullif(trim(coalesce(p_business_name, '')), '') is null then raise exception 'business_name_required'; end if;
  if nullif(trim(coalesce(p_contact_name, '')), '') is null then raise exception 'contact_name_required'; end if;
  if v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'valid_email_required'; end if;
  if p_active_records is null or p_active_records < 0 or p_active_records > 10000 then raise exception 'invalid_active_records'; end if;
  if p_follow_up_problem not in ('missed', 'ownership', 'next_action', 'visibility', 'reporting', 'none') then raise exception 'invalid_follow_up_problem'; end if;
  if char_length(trim(coalesce(p_required_outcome, ''))) < 5 then raise exception 'required_outcome_required'; end if;
  if not coalesce(p_owner_available, false) then raise exception 'owner_availability_required'; end if;
  if not coalesce(p_data_authority, false) then raise exception 'data_authority_required'; end if;
  if not coalesce(p_boundary_accepted, false) then raise exception 'boundary_acceptance_required'; end if;
  if char_length(trim(coalesce(p_request_fingerprint, ''))) < 32 then raise exception 'request_fingerprint_required'; end if;

  if (
    select count(*) from public.tad_applications
    where request_fingerprint = trim(p_request_fingerprint)
      and submitted_at > now() - interval '1 hour'
  ) >= 5 then
    raise exception 'rate_limit_exceeded';
  end if;

  select * into v_existing
  from public.tad_applications
  where lower(email) = v_email
    and submitted_at > now() - interval '24 hours'
  order by submitted_at desc
  limit 1;

  if v_existing.id is not null then
    return jsonb_build_object(
      'id', v_existing.id,
      'duplicate', true,
      'status', v_existing.status,
      'readiness_ready', v_existing.readiness_ready
    );
  end if;

  if p_active_records between 10 and 100 then
    v_score := v_score + 3;
  elsif p_active_records > 100 then
    v_score := v_score + 2;
  end if;
  if p_follow_up_problem <> 'none' then v_score := v_score + 2; end if;
  if p_owner_available then v_score := v_score + 2; end if;
  if p_data_authority then v_score := v_score + 2; end if;
  if p_boundary_accepted then v_score := v_score + 1; end if;

  v_ready := v_score >= 8
    and p_active_records >= 10
    and p_follow_up_problem <> 'none'
    and p_owner_available
    and p_data_authority
    and p_boundary_accepted;

  insert into public.tad_applications(
    business_name, contact_name, email, active_records, follow_up_problem,
    current_tools, required_outcome, owner_available, data_authority,
    boundary_accepted, readiness_score, readiness_ready, source,
    request_fingerprint
  ) values (
    left(trim(p_business_name), 160), left(trim(p_contact_name), 160), v_email,
    p_active_records, p_follow_up_problem, nullif(left(trim(coalesce(p_current_tools, '')), 300), ''),
    left(trim(p_required_outcome), 700), p_owner_available, p_data_authority,
    p_boundary_accepted, v_score, v_ready,
    coalesce(nullif(left(trim(coalesce(p_source, '')), 80), ''), 'sales_admin_offer'),
    left(trim(p_request_fingerprint), 128)
  ) returning * into v_application;

  insert into public.tad_application_events(
    application_id, event_type, to_status, detail
  ) values (
    v_application.id, 'submitted', 'new',
    format('Readiness %s/10; ready=%s', v_application.readiness_score, v_application.readiness_ready)
  );

  return jsonb_build_object(
    'id', v_application.id,
    'duplicate', false,
    'status', v_application.status,
    'readiness_ready', v_application.readiness_ready
  );
end;
$$;

create or replace function public.list_tad_applications()
returns jsonb
language plpgsql
security definer
set search_path = ''
stable
as $$
begin
  if auth.uid() is null or not public.is_tad_operator(auth.uid()) then
    raise exception 'operator_access_required';
  end if;

  return jsonb_build_object(
    'summary', jsonb_build_object(
      'new', (select count(*) from public.tad_applications where status = 'new'),
      'reviewing', (select count(*) from public.tad_applications where status = 'reviewing'),
      'qualified', (select count(*) from public.tad_applications where status = 'qualified'),
      'onboarding', (select count(*) from public.tad_applications where status = 'onboarding'),
      'converted', (select count(*) from public.tad_applications where status = 'converted')
    ),
    'applications', coalesce((
      select jsonb_agg(row_to_json(x) order by x.submitted_at desc)
      from (
        select a.id, a.business_name, a.contact_name, a.email, a.active_records,
               a.follow_up_problem, a.current_tools, a.required_outcome,
               a.owner_available, a.data_authority, a.boundary_accepted,
               a.readiness_score, a.readiness_ready, a.status,
               a.qualification_notes, a.commercial_decision,
               a.managed_business_id, a.source, a.submitted_at, a.updated_at,
               b.name as managed_business_name
        from public.tad_applications a
        left join public.businesses b on b.id = a.managed_business_id
        order by a.submitted_at desc
        limit 250
      ) x
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.update_tad_application(
  p_application_id uuid,
  p_status text,
  p_qualification_notes text default null,
  p_commercial_decision text default 'pending'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_before public.tad_applications%rowtype;
  v_after public.tad_applications%rowtype;
begin
  if v_uid is null or not public.is_tad_operator(v_uid) then raise exception 'operator_access_required'; end if;
  if p_status not in ('new', 'reviewing', 'qualified', 'declined', 'onboarding', 'converted') then raise exception 'invalid_application_status'; end if;
  if p_commercial_decision not in ('pending', 'accepted', 'declined', 'needs_scope') then raise exception 'invalid_commercial_decision'; end if;

  select * into v_before from public.tad_applications where id = p_application_id for update;
  if v_before.id is null then raise exception 'application_not_found'; end if;
  if p_status in ('onboarding', 'converted') and v_before.managed_business_id is null then
    raise exception 'managed_business_required';
  end if;

  update public.tad_applications
  set status = p_status,
      qualification_notes = nullif(left(trim(coalesce(p_qualification_notes, '')), 2000), ''),
      commercial_decision = p_commercial_decision
  where id = p_application_id
  returning * into v_after;

  insert into public.tad_application_events(
    application_id, actor_id, event_type, from_status, to_status, detail
  ) values (
    v_after.id, v_uid, 'review_updated', v_before.status, v_after.status,
    left(coalesce(v_after.qualification_notes, ''), 500)
  );

  return jsonb_build_object(
    'id', v_after.id,
    'status', v_after.status,
    'commercial_decision', v_after.commercial_decision,
    'managed_business_id', v_after.managed_business_id
  );
end;
$$;

create or replace function public.start_tad_application_onboarding(p_application_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_application public.tad_applications%rowtype;
  v_workspace jsonb;
  v_business_id uuid;
begin
  if v_uid is null or not public.is_tad_operator(v_uid) then raise exception 'operator_access_required'; end if;

  select * into v_application
  from public.tad_applications
  where id = p_application_id
  for update;

  if v_application.id is null then raise exception 'application_not_found'; end if;
  if v_application.status not in ('qualified', 'onboarding') then raise exception 'application_must_be_qualified'; end if;

  if v_application.managed_business_id is null then
    v_workspace := public.create_managed_business(
      v_application.business_name,
      'Service business',
      v_application.contact_name,
      v_application.email,
      'sales',
      'setup'
    );
    v_business_id := (v_workspace->>'business_id')::uuid;

    update public.tad_applications
    set managed_business_id = v_business_id,
        status = 'onboarding',
        commercial_decision = 'accepted'
    where id = v_application.id;

    insert into public.tad_application_events(
      application_id, actor_id, event_type, from_status, to_status, detail
    ) values (
      v_application.id, v_uid, 'workspace_created', v_application.status, 'onboarding',
      'Managed Sales Admin workspace created: ' || v_business_id::text
    );
  else
    v_business_id := v_application.managed_business_id;
  end if;

  return jsonb_build_object(
    'application_id', v_application.id,
    'business_id', v_business_id,
    'status', 'onboarding'
  );
end;
$$;

revoke all on function public.submit_tad_application(text, text, text, integer, text, text, text, boolean, boolean, boolean, text, text) from public;
grant execute on function public.submit_tad_application(text, text, text, integer, text, text, text, boolean, boolean, boolean, text, text) to anon, authenticated;

revoke all on function public.list_tad_applications() from public, anon;
grant execute on function public.list_tad_applications() to authenticated;

revoke all on function public.update_tad_application(uuid, text, text, text) from public, anon;
grant execute on function public.update_tad_application(uuid, text, text, text) to authenticated;

revoke all on function public.start_tad_application_onboarding(uuid) from public, anon;
grant execute on function public.start_tad_application_onboarding(uuid) to authenticated;
